### ISSUE TITLE
copying and pasting disk image file doesn't trigger renaming

### ISSUE THREAD

**Issue by danielzhou82** [reorx/obsidian-paste-image-rename#10]
**Describe the bug**
Copying an existing image file (PNG, to be specific) in Finder, and pasting it to markdown, no renaming window shows up.

**Environments (please complete the following information):**
- OS: MacOS
- Use `[[Wikilinks]]`: true
- Debug info:
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1    <----- disable this doesn't solve my problem
	Safe mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Paste image rename

**To Reproduce**
1. copy an existing disk image file
2. paste it to markdown
3. file copied to my default directory and default wikilink inserted, no renaming process triggered

**Expected behavior**
the plugin let me rename the image file

**Screenshots**
not available

**Comment by s-blu** [comment]
I have the same trouble on Windows 10. When I drag and drop an image from the Windows File Explorer onto Obsidian, the file gets inserted correctly, but the rename is not triggered. I have "Auto Rename" and "Handle all Attachments" active. 

It works fine with images I copy i.e. from the browser, but not for the ones I drag onto Obsidian from my file system. Also don't work when I right-click -> Copy and paste into Obsidian.

**Comment by curiosity654** [comment]
> I have the same trouble on Windows 10. When I drag and drop an image from the Windows File Explorer onto Obsidian, the file gets inserted correctly, but the rename is not triggered. I have "Auto Rename" and "Handle all Attachments" active.
> 
> It works fine with images I copy i.e. from the browser, but not for the ones I drag onto Obsidian from my file system. Also don't work when I right-click -> Copy and paste into Obsidian.
> 
> EDIT: Oh dear, I just fixed it for me 😆 When I put _something_ in the "Exclude Patterns" for the handle all attachments input, i.e. `zip`, it renames the files I drag and drop from the explorer correctly. I guess the plugin cannot handle an empty exclude pattern field.

Thx! This works for me too! I'm using MacOS right now.

**Comment by reorx** [comment]
This should be fixed in release 1.5.2, try enabling "handle all attachments" and then drag'n drop an image, or paste an image directly from a file copy to see if it works.
