### ISSUE TITLE
Markdown does not update, windows 10

### ISSUE THREAD

**Issue by martinandersen3d** [reorx/obsidian-paste-image-rename#11]
The File on the disk is correctly renamed. But the new name is not being updated in the markdown file.
I use obsidian in Live Preview mode and not (Reading/Source-mode)

Hardware: Samsung NVmee + Windows

Idears for what this bug can be:
- I suspect that two disk operations is done at the same time, and the first action changes the conditions, faster than action two is able to catch up. 
- Some async file handling, that is not done correctly?
- Maybe a 200 millisec delay, somewhere in the code, can fix that Obsidian or OS can see the new change?

I dont know :-/

`PastedImage-{{DATE:YYYYMMDDhmmss}}`

![image](https://user-images.githubusercontent.com/19984581/170240354-b3e6149b-b01c-4aa8-a42e-c9f5279f997e.png)

**Comment by martinandersen3d** [comment]
I currently open the image in obsidian and rename it in the title, that does also update the markdown. I dont know if you can access obsidians own build in rename tool?  
 

In this screen recording. Notice:

1.  file on disk is renamed when i edit the title
2.  For this recording i Use native Obsidian, without the plugin
3.  the markdown is updated correctly after the rename

  
  
![](https://user-images.githubusercontent.com/19984581/170244921-acf5a9b0-d09a-4d64-81af-670e6c883581.gif)

**Comment by Ch4mpa9ne** [comment]
So do I.

**Comment by reorx** [comment]
Hey guys, this issue should be fixed in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0), please update and try if it works. You can also look at the release log, which contains more details and my sincere gratitude to you.
