### ISSUE TITLE
the picture internal link not updated while disable wikilink

### ISSUE THREAD

**Issue by luckyfatpig** [reorx/obsidian-paste-image-rename#13]
**Describe the bug**
the picture internal link not updated while disable wikilink , the internal link only updated the wikilink setting is enabled
**Environments (please complete the following information):**
- OS: [e.g. Windows 10]
- Use `[[Wikilinks]]`: [true or false, this option locates at `Settings > Files & Links > Use [[Wikilinks]]`]
- Debug info:

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Comment by Kojuda** [comment]
Same problem

**Comment by Zijinn** [comment]
the same problem

**Comment by reorx** [comment]
Hey guys, this issue should be fixed in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0), please update and try if it works. You can also look at the release log, which contains more details and my sincere gratitude to you.
