### ISSUE TITLE
Rename Pattern does not support {{DATE:YYYYMMDD}}-{{fileName}}

### ISSUE THREAD

**Issue by liamtao** [reorx/obsidian-paste-image-rename#16]
**Describe the bug**
When I use pattern like {{fileName}}-{{DATE:YYYYMMDD}}, it works great as expected.
But when I am trying to move date at begining, which pattern looks like:{{DATE:YYYYMMDD}}-{{fileName}}, the image filename
can not be renamed as as expected.  

**To Reproduce**
1. Note Name: "Workbench"
2. use rename pattern: `{{DATE:YYYYMMDD}}-{{fileName}}`
3. The image is renamed as : `20220702}}-{{fi7/2/20226ADam496` which is expected to be ``20220702-Workbench``

<img width="885" alt="image" src="https://user-images.githubusercontent.com/9836684/176985537-a9741765-3a82-4e66-a66d-f25227eb869e.png">

**Comment by huyz** [comment]
Same here.  Bizarre

**Comment by merlinuwe** [comment]
Me too.

SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.1.17
	Snippets enabled: 22
	Restricted mode: off
	Plugins installed: 60
	Plugins enabled: 47
		1: Vault Statistics v0.1.3
		2: Templater v1.16.0
		3: Tag Wrangler v0.5.5
		4: Tasks v1.20.0
		5: Symbols Prettifier v1.1.1
		6: Style Settings v0.4.12
		7: Sortable v0.2.6
		8: Scroll to Top Plugin v1.5.0
		9: Recent Files v1.3.5
		10: Paste image rename v1.5.0
		11: Pandoc Plugin v0.4.1
		12: Obsidian Enhancing Export v1.1.7
		13: Obsidian Camera v1.5.0
		14: Number Headings v1.10.0
		15: Minimal Theme Settings v6.1.1
		16: Media Extended v2.11.1
		17: Linter v1.10.1
		18: Janitor v1.0.7
		19: Homepage v2.6
		20: Find orphaned files and broken links v1.8.0
		21: File Tree Alternative Plugin v2.2.7
		22: Execute Code v1.5.0
		23: Excel to Markdown Table v0.4.0
		24: Editor Syntax Highlight v0.1.3
		25: Editing Toolbar v2.2.3
		26: Dataview v0.5.47
		27: Copy document as HTML v0.3.3
		28: Contextual Typography v2.2.4
		29: Completr v3.1.0
		30: Commander v0.4.9
		31: Calendar v1.5.10
		32: Buttons v0.4.19
		33: Auto Class v2.2.0
		34: Advanced URI v1.31.2
		35: Bulk Rename v0.4.4
		36: DB Folder v3.1.0
		37: Waypoint v1.4.0
		38: Folder Note v0.7.3
		39: Hover Editor v0.11.8
		40: Show Current File Path v0.5.2
		41: Reminder v1.1.15
		42: Text expand v0.11.2
		43: Icon Folder v1.5.1
		44: Excalidraw v1.8.7
		45: MAKE.md v0.5.6
		46: Custom File Explorer sorting v1.4.0
		47: File Explorer Note Count v1.2.0

**Comment by cnyyk** [comment]
THANKS @saezhe FOR PERFECT SOLUTION:
https://github.com/reorx/obsidian-paste-image-rename/pull/18

BEFORE PLUGIN UPDATED, SOLVED IT BY MYSELF:
1. Open folder `.obsidian\plugins\obsidian-paste-image-rename`
2. Edit `main.js`
3. Replace `const dateTmplRegex = /{{DATE:(.+)}}/gm` with `const dateTmplRegex = /{{DATE:([^}]+)}}/gm`
4. Save and close
5. Restart Obsidian

**Comment by reorx** [comment]
Resolved in #18

**Comment by reorx** [comment]
The fix for this issue has been released in [1.5.1](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.5.1)
