### ISSUE TITLE
Bug: "Pasted Image" Pattern not working.

### ISSUE THREAD

**Issue by chrisgrieser** [reorx/obsidian-paste-image-rename#2]
When this toggle is off, the plugin is supposed to work with images that match "Pasted Image" if I understand this correctly? For me that is not the case. I paste an Image with the name `Pasted Image 123.png` into the editor and nothing happens. Only with the "Handle all images" setting enabled, does the plugin work for me.

<img width="1070" alt="Pasted Image 2022-04-18 21 17 12" src="https://user-images.githubusercontent.com/73286100/163863178-8f4c104f-1a11-4070-93ee-840bd22f03f3.png">

**Comment by reorx** [comment]
Thanks for reporting, this is something that I didn't make clear. The name pattern should be "Pasted image" not "Pasted Image", I'll update the description in the next release.

Another thing worth mentioning is that pasting an image from a file behaves differently in macOS and Windows.
In macOS, both pasting from the clipboard and pasting from a file are treated as creating a new image from the clipboard by Obsidian, thus the image is always named as "Pasted image 2022...". But in Windows, which I suppose you are using, pasting from a file is like a regular file transfer, the original name is kept other being created as "Pasted image 2022..." by Obsidian. I'll add some explanation about this in FAQ part of readme.

**Comment by reorx** [comment]
You can try copying an image by right-click an image on the web and selecting "Copy image", or using Windows Snipping Tool to clip part of the screen, then paste it in Obsidian with "Handle all images" unchecked, and see if that works. If not, it's definitely a bug I need to take a deeper look at.

**Comment by reorx** [comment]
[FAQ](https://github.com/reorx/obsidian-paste-image-rename#faq) added, check if that makes it clear.

**Comment by chrisgrieser** [comment]
ah, I see, thanks! I didn't realize that the `Pasted image` pattern is case sensitive. (I am using my own screenshot setup, where I can control the name of the output.)

Thanks for the quick response!
