### ISSUE TITLE
can i use noteid to replace imageNameKey ?

### ISSUE THREAD

**Issue by lin0kin** [reorx/obsidian-paste-image-rename#21]
my note has `noteid` in frontmatter , can i use it to replace `imageNameKey` ?

**Comment by reorx** [comment]
Reasonable suggestion, what do you think about providing a general solution for frontmatter? In your case, it could be used as `{{frontmatter.noteid}}`.

**Comment by lin0kin** [comment]
> A reasonable suggestion, what do you think about providing a general solution for frontmatter? In your case, it could be used as `{{frontmatter:noteid}}`.

for example:

```
---
uuid: 20221214
title: example
---
```

then i can use uuid to replace imageNameKey, the image will be renamed `20221214.jpg`

**Comment by reorx** [comment]
Implemented in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0), check the release log for more details.
