### ISSUE TITLE
Headline variable [Enhancement]

### ISSUE THREAD

**Issue by q7z** [reorx/obsidian-paste-image-rename#26]
Could we add a headline variable?

Rename based on the headline?

That would be amazing, thanks 😊

**Comment by reorx** [comment]
Do you mean the first heading like `# My heading` in the markdown file?

**Comment by reorx** [comment]
Implemented in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0), check the release log for more details.
