### ISSUE TITLE
better duplicate number

### ISSUE THREAD

**Issue by irrealizable** [reorx/obsidian-paste-image-rename#27]
![image](https://user-images.githubusercontent.com/56907077/201520460-aff9f8c6-0753-4de9-9277-9ccf9573cbd9.png)

now my setting is like the above, the atachement names will become
filename.jpg
filename@1.jpg
filename@2.jpg
howover, I wnat it could be like this:
filename@1.jpg
filename@2.jpg
filename@3.jpg

**Comment by reorx** [comment]
Interesting suggestion, I see this as a feature rather than a but, I can add a new setting called "Always add duplicate number", what do you think?

**Comment by irrealizable** [comment]
> Interesting suggestion; I see this as a feature rather than a bug; I can add a new setting called "Always add duplicate number", what do you think?

in fact, I don't know why is a bug, I also see it is a feature. Maybe I made a mistake because I'm not familiar with github.

**Comment by reorx** [comment]
Implemented in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0), check the release log for more details.
