### ISSUE TITLE
non-ascii characters (unicode) disappear

### ISSUE THREAD

**Issue by BigbadHort** [reorx/obsidian-paste-image-rename#28]
**Describe the bug**

**Environments (please complete the following information):**
- OS: Windows
- Use `[[Wikilinks]]`: false
- Debug info: I can`t find command "Show debug info"

Thank you for the wonderful plugin!! I found only one problem - if non-ascii characters (unicode) are used in the file name, then they are simply disappear (you can see in the screenshots). Please add the ability to work with unicode!

![image](https://user-images.githubusercontent.com/7830654/202156415-38c9bb1f-909c-46c2-8010-5c438c469458.png)
![image](https://user-images.githubusercontent.com/7830654/202156464-1dcc06f0-e171-4afc-86d1-aaa02602b6b4.png)

**Comment by merlinuwe** [comment]
I have (nearly) the same issue with german Umlauts öäüÖÄÜß.

If I name this:

![image](https://user-images.githubusercontent.com/4138869/209576950-ea160ced-558b-40de-8853-a7c2e5508755.png)

it gets to:

![image](https://user-images.githubusercontent.com/4138869/209576995-1f982bfe-e4aa-4fa3-bfd5-0759f27139cb.png)

**Comment by merlinuwe** [comment]
Do you need any further information? I'm willing to help.

**Comment by reorx** [comment]
resolved in #32

**Comment by reorx** [comment]
The fix for this issue has been released in [1.5.1](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.5.1)

**Comment by merlinuwe** [comment]
Thank you so much! ;-)
