### ISSUE TITLE
Chinese character disapear

### ISSUE THREAD

**Issue by Zplusless** [reorx/obsidian-paste-image-rename#30]
**Describe the bug**

if I rename an image with Chinese and click the rename button, the Chinese characters in the file name will disappear. PS: Changing image names manually works well.

**Environments (please complete the following information):**
- OS: [e.g. Windows,]
- Use `[[Wikilinks]]`: [true]
- Debug info:

SYSTEM INFO:
	Obsidian version: v1.1.11
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Blue Topaz v20230104
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 41
	Plugins enabled: 37
		1: Note Refactor v1.7.1
		2: Copy Block Link v1.0.4
		3: Convert url to preview (iframe) v0.5.0
		4: Recent Files v1.3.5
		5: Clear Unused Images v1.0.6
		6: Kanban v1.5.1
		7: Excalidraw v1.8.9
		8: Hover Editor v0.11.8
		9: Advanced Tables v0.18.1
		10: Daily Activity v0.4.0
		11: Calendar v1.5.10
		12: Remotely Save v0.3.25
		13: Quick Explorer v0.2.7
		14: QuickAdd v0.8.0
		15: Breadcrumbs v3.6.4
		16: Checklist v2.2.12
		17: Dataview v0.5.53
		18: Tag Wrangler v0.5.6
		19: Custom Frames v2.4.4
		20: ExcaliBrain v0.1.11
		21: Image Toolkit v1.3.1
		22: Find orphaned files and broken links v1.8.0
		23: Minimal Theme Settings v6.1.1
		24: Style Settings v0.4.12
		25: Copy button for code blocks v0.1.0
		26: Dangerzone Writing v0.0.11
		27: Better Word Count v0.9.1
		28: Obsidian42 - Strange New Worlds v1.1.2
		29: Easy Typing v5.1.3
		30: Media Extended BiliBili Plugin v0.3.1
		31: Media Extended v2.11.1
		32: Commander v0.4.9
		33: File Tree Alternative Plugin v2.2.8
		34: Outliner v4.2.1
		35: Tray v0.1.2
		36: Paste image rename v1.5.0
		37: Image Caption v0.0.15.alpha

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**To Reproduce**
1. paste an image into one note
2. input some Chinese characters in the new file name 
3. click the "rename" button
4. the image is inserted, but the Chinese characters in the filename disapear. 

**Expected behavior**

**Screenshots**

the expected file name
![image](https://user-images.githubusercontent.com/10062702/211935694-8779d921-e897-4644-9802-345c1ec86cde.png)

the file name you get
![image](https://user-images.githubusercontent.com/10062702/211935759-d53f1f0b-f3bc-452f-ad2e-d772ba58e772.png)

**Comment by reorx** [comment]
The fix for this issue has been released in [1.5.1](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.5.1)
