### ISSUE TITLE
suggestion: add {{parent-dir}} as placeholder

### ISSUE THREAD

**Issue by c33s** [reorx/obsidian-paste-image-rename#31]
if a picture is pasted into the note `myfolder/mysubfolder/mynote.md` it would be nice to be able to name the image like `mysubfolder-mynote.png` by adding a new placeholder `{{parent-dir}}`

**Comment by reorx** [comment]
Since we are already using the CamelCase for template variables, I suggest naming it as `dirName`, check this commit to see if it is what you expected: 49a970d

**Comment by reorx** [comment]
Implemented in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0)

**Comment by lbg-aubele** [comment]
Is it possible to save the picture inside the "mysubfolder" with this? I tried, but did not succeed.
