### ISSUE TITLE
FR: Command to bulk rename already existing

### ISSUE THREAD

**Issue by chrisgrieser** [reorx/obsidian-paste-image-rename#4]
I really love the consistency by this plugin and was wondering whether it's possible to add a command that renames all images link in the current note, maybe with a customizable pattern, so only images with "bad" names get renamed?

**Comment by reorx** [comment]
Lol, this is a planned feature mentioned [here](https://github.com/reorx/obsidian-paste-image-rename/blob/4d04c7725a50b7dbfb32e7ad273c078f0dbc3ab3/src/main.ts#L8). I'll working on it in this weekend.

The purpose of this feature is to rename all the pasted images in old files with lots of images. But I only considered "Pasted image" as the bad pattern since it's the most common cause. Do you think it's necessary to change the pattern? In that case this functionality may be complicated enough to be a new plugin for generic batch renaming.

**Comment by chrisgrieser** [comment]
> Lol, this is a planned feature mentioned [here](https://github.com/reorx/obsidian-paste-image-rename/blob/4d04c7725a50b7dbfb32e7ad273c078f0dbc3ab3/src/main.ts#L8). I'll working on it in this weekend.

haha, cool! 😆 

> But I only considered "Pasted image" as the bad pattern since it's the most common cause.

yeah, but when you use images from other sources (extracted from a website, etc.) they often have other bad patterns, e.g. `Untitled 1`, `Screenshot 2020-04-31`, `image4` etc. – so I think an option to change the pattern would indeed make sense. not sure whether a new plugin would be necessary though, since  it would use a lot of the functionality offered by this plugin, wouldn't it? 🤔

**Comment by reorx** [comment]
Got it, reminds me that I also downloaded some articles using the MarkDownload chrome extension, the image names are really a mess, I never thought of renaming them, but it's reasonable that other people think it's necessary.

![image](https://user-images.githubusercontent.com/405972/164027417-25c17043-3c40-4ed2-bbbe-655ab2b7f1b7.png)

Here's an example that convinces me to allow customizing the pattern for the batch renaming feature.

> not sure whether a new plugin would be necessary though, since it would use a lot of the functionality offered by this plugin, wouldn't it? 🤔

I may be too overthinking, you are right, let's implement it first, don't need to cover all the cases, just focused what we talked about.

**Comment by reorx** [comment]
This should be good https://imgur.com/6UICugX

**Comment by reorx** [comment]
Hi @chrisgrieser, the batch renaming feature has been added in 1.3.0, feel free to test it.

**Comment by chrisgrieser** [comment]
Hi, that looks useful, but I was rather thinking of a feature where you apply the existing renaming pattern from the settings, i.e. making the batch renaming an issue of simply pressing a hotkey?

**Comment by reorx** [comment]
@chrisgrieser simply pressing a hotkey then all the images in the active note are being renamed using the settings pattern, is that it? And without confirmation?

**Comment by chrisgrieser** [comment]
Yep!

**Comment by reorx** [comment]
There you go, try the `Batch rename all images instantly (in the current file)` command in [1.5.1](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.5.0)

**Comment by chrisgrieser** [comment]
works perfectly, thank you so much 🥳
