### ISSUE TITLE
Request: Extend functionality to other file types

### ISSUE THREAD

**Issue by indiewelt** [reorx/obsidian-paste-image-rename#6]
Hi - First of all, the plugin works perfectly, thank you for the work. 

In order to increase consistency with other attachments, would it be possible to extend the functionality to other file types? E.g. pdf but also docx. or any other attachment? This would allow this plugin to become the main authority of all file name patterns and would increase the usability greatly.

thank you for considering this.

**Comment by reorx** [comment]
Thanks for the feedback, this could be achieved by adding a supported extension list in the settings, and let the user to config which extensions should be handled by this plugin.

I'll notify you when this feature is released.

**Comment by indiewelt** [comment]
Thank you. That is amazing. As an alternative you could potentially deactivate the if function so that it applies to all attachment types (even those which are not supported by obsidian. Eg word as mentioned but also video, excel files etc.

**Comment by Kaijien** [comment]
Thank you for the work.
I also need this function and have some other idea.
I want to set different path according to some rules, such as according to the label of notes or the note folder path
for example:
  if the note have tag 'project', the attachment will move to 'current_note_dir/assets/' , if the note have tag 'card', it will move to 'root/assets/card/' 
I'm not sure if many people need it, but it's useful to me,

**Comment by reorx** [comment]
Hey guys, I just published the [1.4.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.4.0) pre-release to support this functionality, please upgrade and try. I'll update the readme and make it a formal release later.

![image](https://user-images.githubusercontent.com/405972/167308907-0bebba61-d7bd-45b6-abb8-b3447f915540.png)

**Comment by reorx** [comment]
> I want to set different path according to some rules, such as according to the label of notes or the note folder path

@Kaijien this is a planned feature recorded in #1, after this release I'll get back to my own work for a while, so it may not be implemented very soon. June is probably fine, hope you don't feel waiting for too long :)

**Comment by Kaijien** [comment]
> > I want to set different path according to some rules, such as according to the label of notes or the note folder path
> 
> @Kaijien this is a planned feature recorded in #1, after this release I'll get back to my own work for a while, so it may not be implemented very soon. June is probably fine, hope you don't feel waiting for too long :)

Thanks again!  🤝
