### ISSUE TITLE
Can we disable notification

### ISSUE THREAD

**Issue by chenyukang** [reorx/obsidian-paste-image-rename#7]
Hi @reorx , everything works find, nice work.
May I request a trivial feature, disable notification when I paste images.

Maybe we can add one option.

**Comment by reorx** [comment]
Hi @chenyukang, the option "Disable rename notice" has been added in release [1.3.1](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.3.1). Please upgrade and enable this option to see if it works as expected.
